import { test } from "../src/fixtures";

// Generated by Cowork (acting as the playwright-ai agent) — goal: complete a full checkout
// All step code is pre-seeded in .pwai-cache, so this runs without any LLM.
test("complete a full checkout", async ({ page, ai }) => {
  await page.goto("https://www.saucedemo.com");
  await ai(
    [
      'type "{{username}}" into the username field',
      'type "{{password}}" into the password field',
      "click the login button",
      'add the "Sauce Labs Backpack" to the cart',
      "open the shopping cart",
      "click the checkout button",
      'type "{{firstName}}" into the first name field',
      'type "{{lastName}}" into the last name field',
      'type "{{postalCode}}" into the postal code field',
      "click the continue button",
      "click the finish button",
      'verify the order confirmation says "Thank you for your order!"',
    ],
    {
      username: "standard_user",
      password: "secret_sauce",
      firstName: "Abdul",
      lastName: "Aziz",
      postalCode: "12345",
    },
  );
});
