import { test } from '../src/fixtures';

// Generated by the playwright-ai agent — goal: log in
// Steps are cached in .pwai-cache; they replay without an LLM and self-heal on UI changes.
test("log in", async ({ page, ai }) => {
  await page.goto("https://www.saucedemo.com");
  await ai(
    [
        "type \"{{username}}\" into the username field",
        "type \"{{password}}\" into the password field",
        "click the login button",
    ],
      {"username":"standard_user","password":"secret_sauce"},
  );
});
