import { test } from '../src/fixtures';
import { BASE_URL, CREDENTIALS } from '../src/test-config';

// Generated by the playwright-ai agent — goal: login to leadmanager
// URL + credentials come from .env (see .env.example).
// Steps are cached in .pwai-cache; they replay without an LLM and self-heal on UI changes.
test("login to leadmanager", async ({ page, ai }) => {
  await page.goto(BASE_URL);
  await ai(
    [
      "click the login button",
      'type "{{username}}" into the username field',
      'type "{{password}}" into the password field',
    ],
    CREDENTIALS,
  );
});
