import { test } from '../src/fixtures';

// Generated by the playwright-ai agent — goal: test all filter in dashboard
// Steps are cached in .pwai-cache; they replay without an LLM and self-heal on UI changes.
test("test all filter in dashboard", async ({ page, ai }) => {
  await page.goto("https://www.saucedemo.com");
  await ai(
    [
        "type \"{{username}}\" into the username field",
        "type \"{{password}}\" into the password field",
        "click the login button",
        "select the option 'Price (low to high)' from the product sort dropdown",
        "select the option 'Name (A to Z)' from the product sort dropdown",
        "select the option 'Price (high to low)' from the product sort dropdown",
        "select the option 'Name (Z to A)' from the product sort dropdown",
    ],
      {"username":"standard_user","password":"secret_sauce"},
  );
});
